### ISSUE TITLE
Optionally read configuration from environment variables instead of YAML files

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#158]
Calagator relies on a couple of YAML files `themes/default/settings.yml` and `config/secrets.yml` to store its configuration. These were designed to be kept outside of version control — but this poses problems for git-based deployment systems, such as Heroku.

Instead of requiring these YAML files to be present, we should update [SettingsReader](https://github.com/calagator/calagator/blob/master/lib/settings_reader.rb) and [SecretsReader](https://github.com/calagator/calagator/blob/master/lib/secrets_reader.rb) to read values from environment variables.

I propose adding a CALAGATOR_ prefix to each key, so secrets.yml's administrator_email, would come from the CALAGATOR_ADMINISTRATOR_EMAIL environment variable. Nested key names should be concatenated together, so SECRETS.mapping.marker_color, would become CALAGATOR_MAPPING_MARKER_COLOR.

Comments should be added to the [sample secrets](https://github.com/calagator/calagator/blob/master/config/secrets.yml.sample) and [default settings](https://github.com/calagator/calagator/blob/master/themes/default/settings.yml) files showing the corresponding environment variable names for each key.

**Comment by shawnacscott** [comment]
Closed via #296.
