### ISSUE TITLE
Fix the Venue#events_count cache so it's accurate

### ISSUE THREAD

**Issue by igal** [calagator/calagator#20]
The event counts on the /venues and /venues/duplicates pages are sometimes wrong and don't reflect the actual number of events for a given venue. This problem isn't urgent and doesn't break anything, but looks strange.

The trouble is that some code is using raw SQL or #update_attribute(s) to modify associations and the Venue#events_count cache isn't updated with the corresponding changes.

The most likely culprit is the duplicate squasher because it does low-level manipulation of records.

I've added a `rake update_counter_caches` task to temporarily set the correct counts into the caches.

**Comment by shawnacscott** [comment]
Is this still an existing issue?

**Comment by reidab** [comment]
I'm not sure. I believe the reproduction steps for this are:

1. Create multiple events all at the same venue
2. Look at the `events_count` field on the venue record. It should match the number of events created.
3. Use the duplicate squasher to merge all the events into one
4. If the `events_count` field is something other than 1, this issue still exists.
