### ISSUE TITLE
Duplicate venue deletion is failing

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#207]
While trying to delete duplicate Portland Code School venues (by manually searching for "portland code school", clicking on the duplicate venue, and the clicking the "delete" link), I get the following error: "ERROR: Cannot destroy venue that has associated events, you must reassociate all its events first."

This is happening even though all events are reassociated. 

![screen shot 2014-08-23 at 1 40 16 pm](https://cloud.githubusercontent.com/assets/1648967/4021810/673eadc2-2b06-11e4-83cc-616184b46cf5.png)

**Comment by akf** [comment]
I believe this is fixed by https://github.com/stumpsyn/servers/issues/36

@aeschright could confirm.

**Comment by reidab** [comment]
Indeed it is.
