### ISSUE TITLE
Tag_list attributes on a model is deprecated

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#229]
While running tests, this deprecation warning is appearing. I suspect this is coming from the `acts_as_taggable` gem.

`DEPRECATION WARNING: You're trying to create an attribute `tag_list'. Writing arbitrary attributes on a model is deprecated. Please just use `attr_writer` etc. (called from attempt_save? at /calagator/app/models/event/saver.rb:37)`

**Comment by reidab** [comment]
It looks like this is fixed in the version of paper_trail that we're now using.
