### ISSUE TITLE
Drop Ruby 1.9 and 2.0 support

### ISSUE THREAD

**Issue by jc00ke** [calagator/calagator#244]
1 part the desire to cut down CI time, 1 part we'll eventually, hopefully, upgrade to Rails 5, which will most likely require Ruby 2.2+.

I'm not sure what we're running in production, but it might be worth updating that too.

Thoughts?

**Comment by reidab** [comment]
We dropped ruby 1.9 support in #281

**Comment by shawnacscott** [comment]
I believe this is closed via #338. Let me know if I'm wrong and I'll reopen.

**Comment by reidab** [comment]
We still support Ruby 2.0 at the moment, but I don't see a compelling reason to drop it until we get 2.2 support up and running. Leaving this closed.
