### ISSUE TITLE
importing .ICS on the with_heroku branch

### ISSUE THREAD

**Issue by maxogden** [calagator/calagator#25]
hiya!

I'm trying to get a calendar set up for the oakland tech community. I have it running here: http://oaklandar.herokuapp.com

However, I get `ERROR: Unable to import: Unknown error: Validation failed: Title can't be blank` when trying to import a .ics URL from a public google calendar

now im trying to figure out how to run source_parser_ical_spec.rb locally to see if it passes on the with_heroku but I don't have postgres installed. is there a way to run that test in isolation? I would also be grateful for any tips on getting ICS import working

**Comment by shawnacscott** [comment]
Is this still an existing issue?
