### ISSUE TITLE
Fix pain points with Meetup event import

### ISSUE THREAD

**Issue by brainwane** [calagator/calagator#251]
An event imported from Meetup comes without context from the group, e.g., programming language, relevant details for what the event is. If a user tries to edit it, calagator will reject changes because (1) too many links in description (thus spam filter), (2) it doesn't correctly import the end time of the event.

So we need to improve import of Meetup events (edit title, include group name in title, extra links, end time missing, import page should redirect to the event page not the main list, meetup tag importing if possible).

May be related to #16 in that creating a sensible default end time would be a temp workaround for the endtime import problem. :)

(Reid opined that this may end up be an easy beginner task. Also, I split this request out from #245.)

**Comment by reidab** [comment]
Closing this for now. We removed the Meetup parser in #681. I've applied for credentials for the new Meetup API. If we're approved for those, we'll open new tickets about that work.
