### ISSUE TITLE
Calagator Code Sprint: January 3rd, 1-5 PM @ Epicodus

### ISSUE THREAD

**Issue by kcomandich** [calagator/calagator#258]
The next code sprint is scheduled for Jan 3rd, details here: http://calagator.org/events/1250467460

Hope to see you there!

**Comment by shawnacscott** [comment]
Hi all!

The code sprint is today from 1-5 at Epicodus! Hope you can make it.

Unfortunately, I've come down with something, and don't want to pass it on to you fine people, so I'm not 100% sure who (if anyone) in leadership will be attending.

In case you all end up self directed today, please make sure to add notes for this code sprint here: https://github.com/calagator/calagator/wiki/Code-Sprint-Notes-and-Status-Reports

Also, here is the general meeting flow:
* Give introductions, including what people want to work on, and anyone without something they want to do can pick something from the [issue tracker](https://github.com/calagator/calagator/issues) or pair with someone else. For those less code-inclined, there are issues labeled 'tasks', and for beginners, we have a 'beginner-friendly' label. Usually this is when someone takes notes, as mentioned above.
* Work until about half hour from the end, then get back together and recap what you learned and/or did. 
* As part of that, please try and check in your code before you leave, even if it's incomplete. 
* Finally, please choose a date and time (generally two weeks out, give or take, on a Saturday from 1-5 PM) for the next code sprint, and open an issue stating that on our issue tracker.

Thanks in advance for your contributions!

**Comment by tutorazadi** [comment]
Hello,
Unfortunately, I am in the same boat (sore throat).

Will this RSVP get me on the list for the next event when it happens?

~ Azadi

**Comment by reidab** [comment]
Sprint notes added to https://github.com/calagator/calagator/wiki/Code-Sprint-Notes-and-Status-Reports#january-3-2015

Notes for the co-located osbridge work sprint moved to: http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2015/Meetings/2015-01-03-worksprint
