### ISSUE TITLE
Venue#has_full_address? misnamed? bug?

### ISSUE THREAD

**Issue by botandrose** [calagator/calagator#261]
During a recent refactoring (#260), @jc00ke noticed a name and behavior mismatch in the following code:

```ruby
# app/models/venue#150
def has_full_address?
  [street_address, locality, region, postal_code, country].any?(&:present?)
end
```

To match the behavior implied by the method name, `any?` should be replaced with `all?`. This could be a bug. IMO, either the method should be renamed to match the behavior, or vice versa. What is the desired behavior here?

**Comment by reidab** [comment]
I'm happy with that proposal.

**Comment by shawnacscott** [comment]
Has this been fixed?

**Comment by reidab** [comment]
It doesn't look like it: https://github.com/calagator/calagator/blob/master/app/models/calagator/venue.rb#L127-L129
