### ISSUE TITLE
Calagator social media accounts

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#266]
The Calagator twitter account seems to be dormant, and the Calagator blog is as well. It would be great for us to have a strategy around what are goals for those accounts are, and who should be responsible for them. If anyone has thoughts, it would be great to have them documented here. I'd love to work toward a consensus around this during the next code sprint (#258).

For my part, I'd be willing to take on some social media management for Calagator if needed. I'd love to see our code sprints being tweeted, and the notes getting posted to the blog, at the very least.

**Comment by reidab** [comment]
@shawnacscott I've placed the credentials in a file in your home directory on calagator.org. You should be able to `ssh shawnacscott@calagator.org` and get them. As for the blog, if you can send me a wordpress.com username, I can grant you access to it.

Please close this issue once you retrieve the twitter credentials.

**Comment by shawnacscott** [comment]
Thanks Reid!

It asks me for a password when I `ssh shawnacscott@calagator.org`. Will you
be a thte code sprint next weekend? We could troubleshoot this then, if
that works for you.

Also, shawnatyger should work for WordPress.

**Comment by shawnacscott** [comment]
Got this working with some new credentials at the code sprint today. Thanks!
