### ISSUE TITLE
Update OpenHatch information

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#268]
@reidab mentioned [Calagator on OpenHatch](http://openhatch.org/projects/Calagator) in #267, and it appears that many things on that page are outdated. This should be part of codifying strategy and access as mentioned in #266.

**Comment by shawnacscott** [comment]
@aeschright, I think you were poking at this today. Any updates?

**Comment by reidab** [comment]
Opened https://github.com/openhatch/oh-mainline/issues/1674

**Comment by reidab** [comment]
Calling this closed on our end.
