### ISSUE TITLE
Calagator Code Sprint: Saturday, February 7, 1-5PM @Epicodus

### ISSUE THREAD

**Issue by moedu23** [calagator/calagator#279]
The next code sprint is Saturday February 7 at Epicodus. Details here: http://calagator.org/events/1250467568

Also, here is the general meeting flow:

* Give introductions, including what people want to work on, and anyone without something they want to do can pick something from the issue tracker or pair with someone else. For those less code-inclined, there are issues labeled 'tasks', and for beginners, we have a 'beginner-friendly' label. Usually this is when someone takes notes, as mentioned above.
* Work until about half hour from the end, then get back together and recap what you learned and/or did.
* As part of that, please try and check in your code before you leave, even if it's incomplete.
* Also we'll choose a date and time (generally two weeks out, give or take, on a Saturday from 1-5 PM) for the next code sprint, and open an issue stating that on our issue tracker.

Thanks in advance for your contributions!

**Comment by shawnacscott** [comment]
Thanks for contributing, everyone! If you have any additional notes, please [add them here](https://github.com/calagator/calagator/wiki/Code-Sprint-Notes-and-Status-Reports#february-7-2015).
