### ISSUE TITLE
Incorrect title

### ISSUE THREAD

**Issue by SarahJune** [calagator/calagator#294]
The current title of the "WatchKit Workshop" event should be "Portland Open House"

I didn't see a place to edit events so I'm hoping this is the way to do it. Thanks!

**Comment by reidab** [comment]
You can edit events using the "Edit" link in the blue sidebar.

**Comment by reidab** [comment]
Also, I think that "Portland Open House" might be a bit to general of a title. You probably want to identify what group's open house this represents.

**Comment by SarahJune** [comment]
Twice thank you!! Prompt and polite and informative. :)

On Thu, Jan 22, 2015 at 4:37 PM, Reid Beels <notifications@github.com>
wrote:

> Also, I think that "Portland Open House" might be a bit to general of a
> title. You probably want to identify what group's open house this
> represents.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calagator/calagator/issues/294#issuecomment-71128230>.
>



-- 
Sarah Fischer
*Developer Engagement Coordinator | **Code Fellows*
<http://www.codefellows.com/>
