### ISSUE TITLE
Links from RSS are opening up on calagator.stumptownsyndicate.org

### ISSUE THREAD

**Issue by jc00ke** [calagator/calagator#304]

**Comment by jc00ke** [comment]
![calagator events - google chrome_003](https://cloud.githubusercontent.com/assets/18191/6086819/a3a892e8-adf9-11e4-9364-22ede8b8f837.png)

**Comment by reidab** [comment]
It looks like it's detecting the wrong hostname, and that we don't currently have a way to explicitly set one. Populating `config.action_controller.default_url_options` with a `{host: 'calagator.org'}`, where the actual host was specified in the secrets file would do it.

**Comment by shawnacscott** [comment]
I believe this is closed with #322
