### ISSUE TITLE
Impossible to install calagator with vagrant

### ISSUE THREAD

**Issue by nondidju** [calagator/calagator#305]
Hello,

I try to install calagator in a VM through the vagrant file, but when I send "vagrant up" in the calagator folder, I get the following error :

`/usr/share/vagrant/plugins/kernel_v1/config/vm.rb:35:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /usr/share/vagrant/plugins/kernel_v1/config/vm.rb:35:in `forward_port'
	from /home/ben/public_html/calagator/Vagrantfile:28:in `block in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v1/loader.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v1/loader.rb:37:in `load'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:97:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:97:in `block in load'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:94:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:94:in `load'
	from /usr/lib/ruby/vendor_ruby/vagrant/vagrantfile.rb:28:in `initialize'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:580:in `new'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:580:in `vagrantfile'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:365:in `host'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:169:in `block in action_runner'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:33:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:33:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:352:in `hook'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:562:in `unload'
	from /usr/bin/vagrant:176:in `ensure in <main>'
	from /usr/bin/vagrant:176:in `<main>'`

My softwares versions are : debian jessie, vagrant 1.6.5, ruby 2.1.5p273, virtualbox 4.3.18

**Comment by shawnacscott** [comment]
@nondidju I've sent in a pull request that should fix this. Check it out and see if it helps for you!
