### ISSUE TITLE
Calagator Code Sprint: February 21st, 1 - 5 PM, Epicodus

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#307]
Code sprint will be held February 21st. Full details here: http://calagator.org/events/1250467807

**Comment by amypivo** [comment]
Any update on a location? I want to cross post it to RailsBridge and live code solving an issue.

**Comment by reidab** [comment]
I was about to head out to this, but there still isn't a location listed. Are we meeting at Episodes, or elsewhere?

**Comment by shawnacscott** [comment]
It's at Epicodus, sorry everyone.
