### ISSUE TITLE
Meetup for Calagator?

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#310]
At this most recent meetup, I asked several attendees about their contact preferences. Right now, I don't think we're doing a good job of keeping contributors engaged by reminding them when we're having events next.

Especially now that I'll be making sure events happen every 1st and 3rd Saturday (per osbridge/planning#177), I'd like to make it a little easier to keep up with and remind people. 

I think that having a meetup group that cross posts to the existing Google group could allow people already using Meetup to use all the tools they're familiar with, and others to still get reminders automatically. Events on Meetup could then easily be imported to Calgator, and there would be a much happier path to remember who attended and invite them to continue attending and contributing.

There is cost associated with this, and it is not an open source tool. I think it is worth it, though. Meetup groups cost $9.99/month for up to 50 members and 4 organizers, or $14.99 for unlimited members and organizers. I'd be happy to start looking for a sponsor for the cost, if necessary.

Thoughts?

**Comment by shawnacscott** [comment]
@calagator/team-calagator Thoughts? I'd really like to do this and get it set up today at #307

**Comment by reidab** [comment]
I don't like the idea of using Meetup, since one of the reasons we set up Calagator in the first place was to avoid that kind of silo. I'll be downtown in a little bit and we can try to figure out more then.
