### ISSUE TITLE
Search box disappears on small screen sizes

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#324]
![screenshot_2015-01-28-15-09-29](https://cloud.githubusercontent.com/assets/1648967/6316578/198919d2-b9e0-11e4-9654-b458188db14a.png)

**Comment by davidmolina** [comment]
@shawnacscott - I'll take a stab at this.

**Comment by shawnacscott** [comment]
Thanks, @davidmolina! :+1:

**Comment by shawnacscott** [comment]
#337 deals with this

**Comment by reidab** [comment]
Fixed with #407
