### ISSUE TITLE
Text encoding error blows out certain calendar imports (fix included, need help writing specs)

### ISSUE THREAD

**Issue by dpritchett** [calagator/calagator#331]
Hi there!  I worked with a volunteer team in Memphis [porting calagator for a local nonprofit](https://github.com/VolunteerOdyssey/calagator) over the weekend.  We had a great time, thanks for the solid foundation.

We noticed that our client's google calendar import blew up with some text encoding errors:

```rb
Source.find_or_create_from(url: 'https://www.google.com/calendar/ical/volunteerodyssey901%40gmail.com/private-5b29b8a77c1c2542dfeef86db8e4c8c5/basic.ics').create_events!
... snip ...
output error : unknown encoding ASCII-8BIT
output error : unknown encoding ASCII-8BIT
output error : unknown encoding ASCII-8BIT
output error : unknown encoding ASCII-8BIT
... results show up with the majority of our inbound events having been discarded.
```

I "fixed" this [in our project by adding a one-line UTF8ify call](https://github.com/VolunteerOdyssey/calagator/commit/5b1760d21f534ea0d085c9cc29c037ae18da872f#diff-ac299feeb78519eeae42f15c99a3089eR49) to the tail end of the parser base class's `read_url` method:

```rb
-    RestClient.get(url).to_str
+    RestClient.get(url).to_str.
+      encode("UTF-8", :invalid => :replace, :undef => :replace, :replace => "?")
```

I thought this was a legitimate candidate for an upstream patch so I set about writing a spec this morning.  I can't quite figure out how to get the 'bad' input text out of my input URL into a spec file or a fixture so that it still fails.  Whenever I cut and paste the bad text into my specs it winds up not breaking anymore.

N.b. the error was on Event validation as triggered by `Source#create_events!` in the `events.select(&:valid?)` step.  When the event went to validate itself it threw the `ASCII-8BIT` error on the event title.

Any help writing up a useful test case would be welcome :)

cc @joshwlewis and spinnerin from #calagator IRC

**Comment by shawnacscott** [comment]
Thanks for the report/proposed fix! I think you may have meant to cc @aeschright.

By the way, check out #314 if you get a chance. We're planning some big changes to how to use Calagator, and it would be great to get downstream feedback on it!

**Comment by shawnacscott** [comment]
@jc00ke @reidab @aeschright @botandrose, any thoughts on this?

**Comment by botandrose** [comment]
Was able to reproduce failure in a test by using http://github.com/vcr/vcr

```ruby
require 'vcr'

VCR.configure do |config|
  config.cassette_library_dir = "spec/support/fixtures/vcr_cassettes"
  config.hook_into :webmock
end

describe Source do
  it "should be able to handle events encoded in Latin1" do
    VCR.use_cassette("latin1") do
      url = 'https://www.google.com/calendar/ical/volunteerodyssey901%40gmail.com/private-5b29b8a77c1c2542dfeef86db8e4c8c5/basic.ics'
      events = Source.find_or_create_from(url: url).create_events!
      events.should_not be_empty
    end
  end
end
```

If you want to take that and run with it. Calagator definitely shouldn't drop events on the floor if it receives text in an unexpected encoding.

Additionally, it's interesting that the Volunteer Odyssey Google Calendar .ics has its event text content encoded in Latin1 (ISO 8859-1), rather than UTF-8. You may want to look into changing that, if possible. It would sidestep this issue, and play nicer with the rest of the net, which has largely adopted UTF-8.

**Comment by dpritchett** [comment]
Thanks!  I have no idea how VO's google calendar is set up and if we could
change it to use UTF-8.  The VO organization itself is only a few years old.

I will see if I can't leverage your test to build a nice PR.

**Comment by shawnacscott** [comment]
@dpritchett have you had a chance to look at this at all? Thanks again for the report! How are things going in Memphis?

**Comment by reidab** [comment]
Months later, I'm trying to reproduce this and it appears that VO's Google Calendar is now being served as UTF-8 and includes the correct UTF-8 headers. Without being able to find a working repro, I'm going to close this. @botandrose if you still happen to have that VCR capture sitting around, please attach it here and reopen.

From doing a bit of research, it seems like the most common cause for these issues is when the calendar file is encoded in UTF-8, but the Content-Type header doesn't specify this. In these cases, the UTF-8 body can be parsed as if it were Latin1, causing these issues.
