### ISSUE TITLE
Secondary navigation is titled inconsistently

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#345]
The wording and capitalization of the secondary navigation for "Events" and "Venues" is inconsistent.

Events:
* Browse Events
* Add an event
* Import event(s)

Venues:
* Browse venues
* Add a venue

I propose we change them to:

Events:
* Browse events
* Add event
* Import event

Venues:
* Browse venues
* Add venue

**Comment by reidab** [comment]
I'm in favor of changing the capitalization, but I'd like to keep the articles in "Add an event" and "Add a venue"

**Comment by shawnacscott** [comment]
Then I suggest that we "Import an event" as well.

**Comment by reidab** [comment]
I think dropping the parens and moving to just "Import events" might be more accurate. We want to convey the fact that people can drop in an iCalendar feed and get many events imported in one step.

**Comment by shawnacscott** [comment]
TIL you could do that. :+1:
