### ISSUE TITLE
Convert Sass to use @import rather than *=require syntax

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#352]
Per [this conversation](https://github.com/calagator/calagator/pull/351#discussion_r27438076), it would be better to convert out Sass files to use the native `@import` function, so that variables propagate properly without prior knowledge of [the reason to use `@import` rather than `*= require`](https://github.com/rails/sass-rails#important-note).

**Comment by reidab** [comment]
Looking back at that original conversation, we can't just convert to using `@import` for dependencies that are in gems without munging the sass load path. `@import` should be used to bring in any files within the Calagator project (anything in `app/assets/stylesheets`) but not for assets provided by gems.
