### ISSUE TITLE
document how to setup a dummy dev env using the local calagator checkout

### ISSUE THREAD

**Issue by edrex** [calagator/calagator#353]
just dropping the commands here for now

Source: http://bundler.io/git.html
```
bundle config local.calagator /vagrant
bundle config disable_local_branch_check true
```

Change `calagator` line in `Gemfile` to:

`gem "calagator", :github => 'calagator/calagator', :branch => 'master'`

`bundle update`

**Comment by botandrose** [comment]
also possible to use the `path` option:

```
gem "calagator", path: "../calagator"
```

**Comment by reidab** [comment]
You should just be able to run `bundle exec bin/calagator new spec/dummy --dummy` from inside your checkout. This will generate a dummy app in spec/dummy that points the calagator gem at your local checkout.

You can then run migrations and specs from the top-level calagator directory with `rake app:db:migrate` and `rake spec` or `cd` into spec/dummy and run the rails server from there.

**Comment by edrex** [comment]
@botandrose yeah, I used the `:github` keyword because it would work for deployment as well

@reidab is it the `--dummy` flag that makes the generated app's Gemfile point to the local copy of Calagator?

**Comment by botandrose** [comment]
@edrex I was actually confused... was thinking of developing calagator/calagator.org, not calagator/calagator. @reidab's suggested is the recommended way... we need to get that into the README.

**Comment by edrex** [comment]
Thanks guys, this is working for me now. Should `vagrant provision` create `spec/dummy` and migrate the contained `db` for people, so they can run the app right away?

**Comment by reidab** [comment]
I think it's reasonable for vagrant to create `spec/dummy` if it doesn't already exist.

**Comment by nblackburn87** [comment]
After bundle updating, I ran the command @reidab has above. It proceeded to create what looks like a full app, run bundle install, and then tried to `rake db:create`. The output looked like this.

FATAL: role "dummy" does not exist

... long stack trace...

Couldn't create database from Postgres.

**Comment by nblackburn87** [comment]
Regarding my previous comment, I had a Postgres requirement sitting in my railsrc file. Once I moved it out of the way, everything seemed okay.

**Comment by shawnacscott** [comment]
So, as far as I can tell, currently the process of getting set up to work on a new checkout of Calagator is:

* `git clone https://github.com/calagator/calagator.git`
* ` cd calagator`
* `bundle exec bin/calagator new spec/dummy --dummy`
* `rake app:db:migrate`

And then to:

*Run the tests*:
* `rake spec` _(from Calagator root)_ 

*Run the rails server*:
* `cd spec/dummy`
* `bundle exec rails server`

Does that look correct to everyone?

**Comment by shawnacscott** [comment]
Looks like we may also need to add something to the running the test section about Poltergeist?

I'm getting:
````
Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       ReferenceError: Can't find variable: L
       ReferenceError: Can't find variable: L
           at http://127.0.0.1:55349/assets/application.js:29235
           at http://127.0.0.1:55349/assets/application.js:29326
````

I seem to already have `phantomjs` installed. Any additional steps?

* `brew install phantomjs`
* ?

**Comment by botandrose** [comment]
That's a JavaScript error, so phantomjs is definitely installed and working. I believe that error points to the JavaScript mapping system. `L` being undefined makes me think that the mapping libraries aren't being loaded, so I think this is another symptom of #350. Can you get this failure replicated in a test?

**Comment by shawnacscott** [comment]
Realized I was running the specs on my branch for #357, so can probably be disregarded for this particular issue. Sorry!
