### ISSUE TITLE
Sprockets::Rails::Helper::AssetsFilteredError

### ISSUE THREAD

**Issue by nblackburn87** [calagator/calagator#364]
Starting from a fresh install I followed along with @shawnacscott's directions in #353. After starting the server, I received this error.

`Sprockets::Rails::Helper::AssetFilteredError in Calagator::Site#index`
`Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( leaflet.js )` to `config/initializers/assets.rb` and restart your server`

I ended up having to create an `assets.rb` file manually in `~/config/initializers` and include the `leaflets.js` that way in addition to `markers-soft.png`,`markers-shadow.png`, `markers-soft@2x.png`, and `markers-shadow@2x.png`. Once they were all included, my dev environment loaded properly.

These are all assets used in `leaflet.awesome-markers.css.scss`. This error feels very similar to #350 and I suspect there's a way to config the setup so that making and including these manually isn't required.

[Full trace is here.](https://gist.github.com/nblackburn87/9a4f014d418161d8fc8d)

**Comment by shawnacscott** [comment]
I also had this same issue. Manually adding `Rails.application.config.assets.precompile += %w( markers-soft.png markers-shadow.png markers-soft@2x.png markers-shadow@2x.png leaflet.js )` to the `/spec/dummy/initializers/assets.rb` file allowed the app to run again.

**Comment by shawnacscott** [comment]
[This discussion](https://github.com/modeset/teaspoon/issues/197#issuecomment-53386365) leads me to believe that maybe 

````
unless Rails.env.production?
  Rails.application.config.assets.precompile += %w( 
    markers-soft.png 
    markers-shadow.png 
    markers-soft@2x.png 
    markers-shadow@2x.png 
    leaflet.js 
  )
end
````
is the solution we need?
