### ISSUE TITLE
Is the delete supposed to be secured?

### ISSUE THREAD

**Issue by jcriddle4** [calagator/calagator#368]
I saw some spam on the site related to "loans with bad credit" or something like that and I noticed a delete button. I clicked the delete link and it worked. I was not logged into the site.Is any user supposed to be able to delete any event?

**Comment by shawnacscott** [comment]
@jcriddle4 Yep, open site gardening is one of the tenets of this project. 

(Don't worry; admins can roll back malicious changes or lock events if they are repeatedly changed)

**Comment by jcriddle4** [comment]
Very cool. Thanks
