### ISSUE TITLE
Collective Agency tech-related venue events were all deleted since 2015

### ISSUE THREAD

**Issue by alexlinsker** [calagator/calagator#369]
Since the start of 2015, every single Collective Agency event that is tech-related has been deleted. That includes meetups, rentals, and no-charge events, that are specific to various programming languages. How can we get events specific to tech, to stay up on Calagator (or at least get notifications when events are deleted, and have a way to save and restore them)? P.S. I will be adding the tech events back to the archives as best I can, unless told not to.

**Comment by reidab** [comment]
I don't think this has been any sort of policy change or intentional removal on our side. Can you give an example of an event that was removed so that I can check the logs?

Were these events that were added to Calagator directly, or were they being imported from an external calendar?

**Comment by alexlinsker** [comment]
Thanks Reid. The events are created by various organizers, I think
directly. I found the issue and can fix it.

I looked into it more and found a duplicate venue name was created and was
storing those more recent events. I'll duplicate those events and attach
them to the original venue name, delete the originals, then delete the
duplicate venue name.

--
Alex Linsker
Collective Agency <http://collectiveagency.co> & Fully Fund Oregon Schools
<http://fullyfundoregonschools.org>
(503) 517-6900 office | (503) 369-9174 mobile
322 NW Sixth Ave, Suite 200 | Portland, Oregon 97209

**Comment by reidab** [comment]
There's an easier way to deal with the duplicate venue. One sec — I'll merge them.

**Comment by alexlinsker** [comment]
Thank you!

--
Alex Linsker
Collective Agency <http://collectiveagency.co> & Fully Fund Oregon Schools
<http://fullyfundoregonschools.org>
(503) 517-6900 office | (503) 369-9174 mobile
322 NW Sixth Ave, Suite 200 | Portland, Oregon 97209
