### ISSUE TITLE
Form labels get cut off on mobile screens.

### ISSUE THREAD

**Issue by PatHarryUX** [calagator/calagator#371]
At http://calagator.org/events/new 

Form labels are cutoff. (iPhone5 screenshot attached)

![2015-05-16 13 53 13](https://cloud.githubusercontent.com/assets/11338556/7667929/5f291d36-fbd3-11e4-9e03-d02584dd5003.png)

**Comment by creationrose** [comment]
Interesting. It works fine on the iphone 6.  Is it fixed for you? If not I will check and see what adjustments can be done..

**Comment by shawnacscott** [comment]
I can confirm on my iPhone 4S and by resizing a desktop browser that this is still an issue. I had a pull request a while ago to address some of this, but it was so out of date and untended to that I closed it. It may be a useful reference point, though: #205

**Comment by PatHarryUX** [comment]
Here's a mockup of how the "Add an Event" screen be optimized for usability on a mobile view:

![add an event](https://cloud.githubusercontent.com/assets/11338556/8021061/6a3ab2ec-0c46-11e5-98fa-e2ca79e7d7fa.png)

**Comment by reidab** [comment]
This was fixed by #413. Thanks!
