### ISSUE TITLE
Country field on venue edit form is very large

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#404]
![screenshot 2015-06-11 11 46 25](https://cloud.githubusercontent.com/assets/13192/8115333/7d4ae0f4-102f-11e5-9388-4f530124a2f3.png)

**Comment by jmcduffie32** [comment]
As long as there isn't a particular reason that country should be a textarea instead of a string, I've fixed this with PR#405.

**Comment by reidab** [comment]
Merged!
