### ISSUE TITLE
Three spam events today

### ISSUE THREAD

**Issue by maryannet** [calagator/calagator#417]
I am not sure what to do about three male enhancement events from 2 to 3 pm
![screen shot 2015-06-16 at 1 18 24 pm](https://cloud.githubusercontent.com/assets/632993/8193535/5bca370a-142a-11e5-8890-ccd919d50f44.png)

**Comment by reidab** [comment]
Please delete them — we can probably extend the existing regular expression to include the underscores…

**Comment by botandrose** [comment]
Just a brief note: I've had success with a home grown anti spam solution that uses JavaScript to add a hidden field to the form after a five second delay. If that field doesn't exist after submission, it's considered spam. Would only work for html form based submissions, but most spam seems to target that, anyways. Might be worth considering here.

**Comment by reidab** [comment]
Interesting. We're already using a hidden text field that has to be left blank or things will be considered spam, but I like this variation…
