### ISSUE TITLE
Styling of venue autocomplete widget is broken

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#421]
The list of autocompleted venues should not include bullets and should be limited in width to the width of the parent text field.

![screenshot 2015-06-19 11 12 02](https://cloud.githubusercontent.com/assets/13192/8259818/2e4dba9e-1674-11e5-8d89-60ce6ea6a03e.png)

**Comment by jmcduffie32** [comment]
Fixed this with #422

**Comment by shawnacscott** [comment]
closed with #422
