### ISSUE TITLE
Importing events from Facebook fails

### ISSUE THREAD

**Issue by gpbenton** [calagator/calagator#430]
I'm creating a new instance of calagator, but importing from Facebook fails, both on my test machine and on my openshift version.

Adding 

https://www.facebook.com/events/1571326959816575/ 

to import  URL results in

ERROR: Unable to import: Unknown error: 400 Bad Request

After a bit of digging around the code, I tried sending

https://graph.facebook.com/1571326959816575/  

in my browser, which resulted in 

    {
       "error": {
          "message": "An access token is required to request this resource.",
          "type": "OAuthException",
          "code": 104
       }
    }

which may or may not be relevant.  I can't see any way of configuring an access token for Facebook.

**Comment by reidab** [comment]
When we originally implemented this, Facebook didn't require authentication for public events (which is all we wanted to support for Calagator), but it looks like that has now changed.

**Comment by lindsaycaron** [comment]
The FB import broke and was fixed and broke again twice while I was using it. Speculation was that FBs frequent updates make it hard to keep up with field matching. 

I had a really wonky work around for this. You can import an ical feed from your FB event feed. Sure, I don't want everything to which I am personally invited to show up on the community calendar, so we created a fake FB account and sent relevant invites to that account. (Just invited someone to a FB event will import it through their ical feed.)
