### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#433]
Putting our contribution guidelines and information in a file called CONTRIBUTING.md will enable a bit of [special behavior](https://github.com/blog/1184-contributing-guidelines).

**Comment by shanirivers** [comment]
Hi, I would like to help out with this. Please let me know what it needs to say or if it just a generic guidelines.

**Comment by reidab** [comment]
I was hoping to be able to point you at existing documentation for this, but it looks like the most relevant page we have (https://github.com/calagator/calagator/wiki/Submitting-a-Pull-Request) is also somewhat out of date. Instead of the workflow described there, we should be telling people to do something along these lines: 

1. work in a fork
2. create a new branch for their feature
3. finish feature work and create a pull request, referencing the original ticket if relevant
4. wait for automated tests to run on travis-ci.org. The results will be reported back to the PR: ensure all tests pass and that the reported test coverage does not decrease

Once we have this figured out for CONTRIBUTING.md, we should also update that wiki page to match this workflow.

In CONTRIBUTING.md, I'd also want to see a mention of our [Code of Conduct](https://github.com/calagator/calagator/wiki/Code-of-Conduct) and a reminder for people to add their names to the [contributors list](https://github.com/calagator/calagator/blob/master/CONTRIBUTORS.md)

**Comment by nblackburn87** [comment]
I'm working on this right now @reidab, since it seems available still. I've got it sitting in a fork right now but I've forgotten so much Git that I need to double check that I'm doing everything correctly.

**Comment by reidab** [comment]
@nblackburn87 sounds good. Thanks!

**Comment by reidab** [comment]
I'd like to get this merged soon. @nblackburn87 can you create this PR: https://github.com/calagator/calagator/compare/master...nblackburn87:contributing ?

Thanks!
