### ISSUE TITLE
calagator executable not installed outside of calagator repo

### ISSUE THREAD

**Issue by antislice** [calagator/calagator#440]
This means that the [install instructions](https://github.com/calagator/calagator/blob/master/INSTALL.md) don't work.

I installed the calagator gem, and then tried to run `calagator new` as mentioned in the install instructions. It failed, because installing the calagator gem didn't install anything into the bin/ directory in my gems directory. I'm not an expert in gem packaging, but looking at the [rubygems guide](http://guides.rubygems.org/make-your-own-gem/#adding-an-executable) the gemspec is missing a line to export it.

To make this work, it looks like the executable itself will need a little reworking to accommodate for a different relative location for the rails_template.rb file.

Workaround: running `bin\calagator new your_cal_name_here` inside your forked calagator repo and copying the resulting rails app to your preferred directory.

**Comment by reidab** [comment]
Good catch! I somehow ended up with it in my bin path, but I think that may be due to a trick of my environment. We should definitely update the gemspec to include `s.executables << 'calagator'` and make sure the requires work correctly.

**Comment by alexandraleigh** [comment]
Notch8 is currently working on the Calagator project from a forked repo. We managed to fix this issue on this branch: https://github.com/notch8/calagator/tree/fix_calagator_executable. We are currently waiting for internal code review before submitting a pull request.
