### ISSUE TITLE
JSONP support not working

### ISSUE THREAD

**Issue by matthewkmayer** [calagator/calagator#441]
The JSONP callback implementation on agilepdx.org has been broken for a few months.  Looks like the callback request isn't being properly handled.

```
curl -i "http://calagator.org/events/search.json?tag=agilepdx&callback=jsonp1437061130040&_=1437061130137"
HTTP/1.1 422 Unprocessable Entity
```

No `callback` in the request and you get data:

```
curl -i "http://calagator.org/events/search.json?tag=agilepdx&_=1437061130137"
```

with a `HTTP/1.1 200 OK`.

Related to https://github.com/calagator/calagator/pull/412 and https://github.com/calagator/calagator/pull/411 ?

**Comment by matthewkmayer** [comment]
I'd be happy to test this when it hits production at calagotor.org.  Just let me know!

**Comment by reidab** [comment]
@matthewkmayer I just deployed this code to http://calagator.org — if you run into any issues now, please let me know.

**Comment by matthewkmayer** [comment]
Looks to be working again: I see the call going out and coming back with data.  I think there's more tweaks to be made on the client call as it returns 134 items and our current javascript doesn't parse it.

Thanks for the fix!

**Comment by reidab** [comment]
:tada:
