### ISSUE TITLE
Development: Vagrant box issues

### ISSUE THREAD

**Issue by matthewkmayer** [calagator/calagator#444]
From HEAD of master:

```
git reset --hard
```

```
vagrant up
```

Then following https://github.com/calagator/calagator/blob/master/DEVELOPMENT.md :

Possibly unrelated error in the provisioning shell script: 
```
The following extra packages will be installed:
==> default:   libmysqlclient18 mysql-common
==> default: The following NEW packages will be installed:
==> default:   libmysqlclient-dev libmysqlclient18 mysql-common
==> default: 0 upgraded, 3 newly installed, 0 to remove and 155 not upgraded.
==> default: Need to get 1,475 kB of archives.
==> default: After this operation, 9,218 kB of additional disk space will be used.
==> default: Do you want to continue?
==> default:  [Y/n] 
==> default: Abort.
```

Due to no -y in

```
apt-get install libmysqlclient-dev
```

Also:

```
Bundler could not find compatible versions for gem "lucene_query":
==> default:   In Gemfile:
==> default:     calagator (>= 0) ruby depends on
==> default:       lucene_query (= 0.1) ruby
==> default: Could not find gem 'lucene_query (= 0.1) ruby', which is required by gem
==> default: 'calagator (>= 0) ruby', in any of the sources.
```

... but lucene_query appears to install with a later command.

```
vagrant ssh
```

```
bundle install
```

```
bundle exec bin/calagator new spec/dummy --dummy
```

This bundle exec command asks to overwrite a bunch of files such as Gemfile and db/seeds.rb.  I've tried allowing overwrite and not allowing overwrite and both give the same results below.

Next step:

```
bin/rake app:db:migrate app:db:test:prepare
-bash: bin/rake: No such file or directory
```

So I run

```
rake app:db:migrate app:db:test:prepare
```

and it completes.  Then

```
rake app:db:seed
```

Then it's on to the tests:

```
rspec
```
Which gives

```
Could not find debug_inspector-0.0.2 in any of the sources
Run `bundle install` to install missing gems.
Coverage report generated for RSpec to /vagrant/coverage. 2 / 2 LOC (100.0%) covered.
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- term/ansicolor (LoadError)
```

Ignoring tests that don't run for now, run calagator:

```
spec/dummy/bin/rails server
```

gives

```
Could not find debug_inspector-0.0.2 in any of the sources
Run `bundle install` to install missing gems.
```

Running `bundle install` doesn't make the spec server command work.

Try with bundle exec:

```
bundle exec spec/dummy/bin/rails server
```

and now calagator is up.  But you can't get to the guest OS from the host OS, curling localhost:3000 fails.  A curl of that from inside the VM works.

There's a lot of documentation that doesn't match what's required and I'm not sure what's noise and what's actually required.  I'm happy to help sorting it out but will need help.

**Comment by matthewkmayer** [comment]
Hey all, this is blocking me from helping with https://github.com/calagator/calagator/issues/441 .  I'd love to give a hand but am stuck right now.

**Comment by matthewkmayer** [comment]
Ping!

**Comment by reidab** [comment]
Hi Matthew — sadly, I don't have a quick answer on the vagrant issues at the moment. I haven't ever used it for development and probably won't have a chance to dig into this in the next few weeks (but I'm happy to review and merge PRs with fixes.)

That said, I'm going to ping @edrex here so that he sees this issue. He's done most of the recent work with Vagrant and may be able to point you in the right direction or propose a fix.

**Comment by matthewkmayer** [comment]
Anything I can do to help this along?  Shall I open another ticket for updating https://github.com/calagator/calagator/blob/master/DEVELOPMENT.md since those instructions don't work?  If I can get traction on any of the three issues (#441, #444, DEVELOPMENT.md being out of date or broken) I'd be quite happy.

**Comment by reidab** [comment]
I just made a couple of small updates to DEVELOPMENT.md (removing the `bin/` prefix from some commands and adding `bundle exec`) and can confirm that they now work for me outside of Vagrant.

**Comment by matthewkmayer** [comment]
Thanks, will take a look at the changes.

**Comment by matthewkmayer** [comment]
The updates to the development.md file work, thanks!

Some notes for me when I make a PR for this issue:

Add the -y as mentioned in original comment, and run the server with -b 0.0.0.0 to allow the host OS to reach the Vagrant box.  By default it binds to 127.0.0.1 so the host requests aren't handled.

```bash
bundle exec spec/dummy/bin/rails server -b 0.0.0.0
```

To do: figure out why a curl to localhost:8000 on host OS gives a 500:

```
Showing /vagrant/app/views/layouts/calagator/application.html.erb where line #28 raised:

Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```

I think I've figured that out before.
