### ISSUE TITLE
Rollback of destroyed events, while successful, leads to 500 error ... with confused alligator image not found (calagator.org)

### ISSUE THREAD

**Issue by akf** [calagator/calagator#446]
I rolled back a few erroneously destroyed events on calagator.org this morning. Each time, I got a 500 server error page (Egads!). In addition, the page had a link to http://calagator.org/assets/confused-alligator-sm.png that was 404. 

The rollback itself appeared to be successful, although it is possible something subtle went wrong.

**Comment by akf** [comment]
Apparently Audrey is seeing similar behavior, but "only in Firefox." I would have been using Firefox as well.

**Comment by EnriqueEsparza** [comment]
Took a look at this, everything appears to be working ok.  We could not reproduce error using FF v.38.0.1 or v.39. What version of Firefox was used??

**Comment by akf** [comment]
Thanks for looking into it. I can't reproduce it today using Firefox v.39. I don't know what version I was using when I noticed the problem, unfortunately. 

So, possibly a firefox update fixed it. I'll re-open if I see the problem again.
