### ISSUE TITLE
INSTALL.md file is outdated

### ISSUE THREAD

**Issue by iamBalaji** [calagator/calagator#452]
The method of installation is outdated and doesn't work now.The gem Calagator must be added in the Gemfile of the rails app and must be proceeded further.Did anyone facing the same problem as I face?
![selection_005](https://cloud.githubusercontent.com/assets/6650280/9540335/4879f4c6-4d7b-11e5-9160-dc3aefa8f789.png)

**Comment by iamBalaji** [comment]
I have created a pull request at #456 for this issue.Verify it.

**Comment by reidab** [comment]
Thanks for submitting this. I think, however, that it would be better to solve #440 and make the existing install instructions work as expected.
