### ISSUE TITLE
Imported events with > 3 URLs in description are uneditable

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#487]
One of our current spam-fighting measures is a limit on the number of links allowed in an event's description. We don't enforce this limit when importing events, since the user doesn't have control over the import source. If an event is imported with more URLs than the allowed limit, subsequent attempts to edit it are rejected.

## Repro

1. Import an event with many links: http://www.meetup.com/laruby/events/226450232/
2. Attempt to edit the event

**Comment by reidab** [comment]
This was spawned from discussion on #251 / #485

**Comment by supremebeing7** [comment]
I was looking into patching this, and wanted to run by a possible solution before coding. Also, I haven't contributed for awhile, so hopefully I'm still understanding how importing works...

It seems to me that each imported event belongs to a source, whereas events that were not imported will have no associated source. If this is correct, can we then bypass the `too_many_links?` spam fighting method and allow it to save? But we would want to ensure the `evil_robot?` check still occurs. 

The only gotcha with this approach is that then someone could import an event, then change absolutely everything about the event and post as many links as they want. To combat that kind of thing, we could utilize ActiveRecord::Dirty and check if more links were added than were originally present. If the same number or fewer links are present for an imported event, then allow successful save. 

There is still some potential for abuse - a user imports an event with 8 links, replaces all 8 with their own and saves. However, I think that might be an acceptable spam risk for the tradeoff of being able to edit the event.

Thoughts?

**Comment by reidab** [comment]
I'm open to trying this change. If it actually ends up letting in spam, we can move from there. :+1:
