### ISSUE TITLE
Spam keywords in urls getting around blacklist?

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator#490]
I found a spam venue in the changelog that seems like it might be getting missed by our blacklist because all the offending words are in the urls.
![screen shot 2015-11-11 at 7 35 11 pm](https://cloud.githubusercontent.com/assets/16411/11109976/8c1682d8-88ab-11e5-9db4-d78977fabcfc.png)

**Comment by reidab** [comment]
It looks like https://github.com/calagator/calagator.org/blob/master/config/blacklist.txt has `\b` around each line, ensuring there's a word boundary. It probably makes sense to remove those from at least all of the drug names.

**Comment by reidab** [comment]
While I'm looking at the blacklist, I may also try removing `cannabis` and see if any spam shows up, since there are likely to be more legitimate events discussing that now…
