### ISSUE TITLE
Not able to import Meetup events

### ISSUE THREAD

**Issue by JamesCSmithPDX** [calagator/calagator#506]
The last two weeks I have tried to use Import with a meetup event but I get an error message:

ERROR: Unable to find any upcoming events to import from this source

**Comment by sciurus** [comment]
Maybe the API mention in #486 has been shut down.

**Comment by turoczy** [comment]
Just figured this out. It's the "https://" that causes the error. Change the URL to "http://" and Meetup imports just fine. 

Hope that helps,
Rick

**Comment by reidab** [comment]
That should be a particularly easy fix. Working on it now. 🎉
