### ISSUE TITLE
No listing for Automacon

### ISSUE THREAD

**Issue by tlehman** [calagator/calagator#508]
This seems like it should be listed: http://www.automacon.io/

**Comment by cp** [comment]
@tlehman http://calagator.org/events/new

**Comment by tlehman** [comment]
Ah, I didn't realize that existed, thanks! http://calagator.org/events/1250470854

**Comment by tlehman** [comment]
How does calagator deal with spam?

**Comment by reidab** [comment]
Like this: https://github.com/calagator/calagator/wiki/Preventing-Spam
