### ISSUE TITLE
Incorrect CSS property for external site tags

### ISSUE THREAD

**Issue by jhelwig** [calagator/calagator#516]
Am I missing something, or is https://github.com/calagator/calagator/blob/57489f41b6b308b256f4d1b3e9dff3c5d37d8ee3/app/assets/stylesheets/calagator/typography.scss#L205-L216 supposed to be `background-image` not `background-`? @reidab?

**Comment by reidab** [comment]
I'm pretty sure it should be `background-image`

**Comment by jhelwig** [comment]
Opened #517 to address.
