### ISSUE TITLE
Unsuccessfully Deleting a Venue

### ISSUE THREAD

**Issue by TiEOregon** [calagator/calagator#525]
I've tried unsuccessfully to delete the TiE Pearl Incubator and TiE Westside Incubator venues however they keep showing up.  Can someone please delete these locations as they are no longer valid.

Thank you very much!

**Comment by reidab** [comment]
These venues couldn't be deleted because it would break the record of all the past events in the system that had been held there. I've updated both venues to indicate that they're closed.

* https://calagator.org/venues/202393268
* https://calagator.org/venues/202394041

**Comment by botandrose** [comment]
Sounds like maybe something like soft-delete should be implemented?

**Comment by TiEOregon** [comment]
Thank you!
