### ISSUE TITLE
Error when submitting iCal link for import events.

### ISSUE THREAD

**Issue by IAmLoisLane** [calagator/calagator#529]
Hello,
I am getting an error message when I try to import my iCal link (webcal://metroeast.org/events/cal.ics or http://metroeast.org/events/cal.ics)

The error I get is:
ERROR: Unable to import: Unknown error: "\xC2" from ASCII-8BIT to UTF-8

My systems guy tells me it shouldn't be converting, so that this is an issue I should contact the Calagator team with.

Thank you!

**Comment by mjang** [comment]
I am getting a different error message when I try to import a Meetup link (ERROR: Unable to import: Unknown error: Invalid parameter value "#39")

**Comment by aeschright** [comment]
I'm sorry you ran into this. Without the .ics file that produced the error, I can't verify the bug. If it happens again, please open another ticket! We'll need the exact data in order to look at it.
