### ISSUE TITLE
[outage] calendar feed is down

### ISSUE THREAD

**Issue by chrishough** [calagator/calagator#532]
<img width="480" alt="screen shot 2017-11-09 at 9 48 14 am" src="https://user-images.githubusercontent.com/744056/32620690-33664cd8-c533-11e7-9081-46b464fb08a6.png">

When you try to subscribe the event calendar you get this error. As an event organizer this view is critical to avoid local event collisions.  I have reached out to @reidab via the startups slack as well.

**Comment by reidab** [comment]
Removed the problematic data, but the root cause still exists #533

**Comment by chrishough** [comment]
It is working now, thanks @reidab
