### ISSUE TITLE
Stumptown Syndicate domain (breaks recaptcha)

### ISSUE THREAD

**Issue by tloudon** [calagator/calagator#535]
Hi @reidab, I was trying to edit the Tuesday April 3rd pdxrb meetup and kept seeing 
![screen shot 2018-03-30 at 10 03 10 am](https://user-images.githubusercontent.com/415007/38146246-15675fea-3402-11e8-84c3-b0c62bc442b9.jpg).  Thought initially the API key had expired or something along those lines, but I think it's an issue w/ links on browse events sometimes saving or generating w/ the wrong domain.

I noticed the URL was http://calagator.stumptownsyndicate.org/events/1250473455 not http://calagator.org/events/1250473455 , but I didn't go to  calagator.stumptownsyndicate.org originally.  I was able to resolve my issue by going directly to the calagator.org URL version.  Perhaps there should be a permanent redirect from the calagator.stumptownsyndicate.org subdomain as it's inoperable for write/edit ops AFAICT (maybe it's a test/staging site tho)?

Anyway, I just wanted to give you a heads up.  Seems possible someone else might get stuck on the stumptownsyndicate version.

Thanks!

**Comment by aeschright** [comment]
I want to move this over to https://github.com/calagator/calagator.org since it relates to the calagator.org setup rather than the gem itself.

**Comment by reidab** [comment]
This was fixed when we migrated off of the Syndicate servers.
