### ISSUE TITLE
Address Gemnasium move to GitLab

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator#548]
We have a widget in our README file that links to https://gemnasium.com/calagator/calagator. It's labeled "dependency status". According to https://docs.gitlab.com/ee/user/project/import/gemnasium.html there's a way to set up a similar service on GitLab, but I want to figure out if this is the best option given the other tools we have available and in use.

**Comment by reidab** [comment]
The biggest value we were getting from Gemnasium in the past was security alerts, which GitHub now offers internally.

**Comment by aeschright** [comment]
Ah, that makes sense. I'll remove it.
