### ISSUE TITLE
Logo images at foot of "About" page are broken

### ISSUE THREAD

**Issue by jmeowmeow** [calagator/calagator#550]
duplicate of #539 which is also a broken image report?

page from which missing: http://calagator.org/about
sample missing image URL: http://calagator.org/assets/tag_icons/ruby.png

(alongside all other logo images at the foot of the about page)

**Comment by aeschright** [comment]
Ah, the asset pipeline ... looks like we have a bunch of HTML image tags that need to be converted to use the Rails helper. I'll work on cleaning that up.

**Comment by aeschright** [comment]
Fixed by https://github.com/calagator/calagator.org/commit/9915b80515dd63ea9c2d185d5b600955718b8b81
