### ISSUE TITLE
Update Capybara javascript driver

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator#553]
On running the tests locally I found I was getting a number of errors:
``` 
1) JSONP API results User requests events.json with a JSONP callback specified
     Got 0 failures and 2 other errors:`

     1.1) Failure/Error: visit "/events.json?callback=myFunction"`
          
          Cliver::Dependency::NotFound:
            Could not find an executable ["phantomjs"] on your path.
          # ./spec/features/jsonp_output_spec.rb:6:in `block (2 levels) in <top (required)>'
          # ./spec/spec_helper.rb:135:in `block (2 levels) in <top (required)>'
```
Here's spec_helper.rb:

```
  require 'capybara/poltergeist'
  Capybara.register_driver :poltergeist do |app|
    Capybara::Poltergeist::Driver.new(app, timeout: 90)
  end
  Capybara.javascript_driver = :poltergeist
```

So I went to find out what I should be installing, since it's been a while. According to this, PhantomJS is severely deprecated: https://github.com/teamcapybara/capybara#poltergeist

I'm going to switch it over to Selenium unless someone has a strong preference otherwise.
@reidab @shawnacscott @jc00ke

**Comment by jc00ke** [comment]
I'm partial to headless Chrome, so `:selenium_chrome_headless` would be my preference.

**Comment by jc00ke** [comment]
In another project, I had to add a bit more to my `spec/features_helper.rb` file under `RSpec.config`

```ruby
Capybara.register_driver :chrome do |app|
    args = %w[disable-gpu no-sandbox, --window-size=1240,1400]
    args << "headless" unless ENV["CHROME_HEADLESS"]

    capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
      chromeOptions: {
        "args" => args,
      },
    )
    Capybara::Selenium::Driver.new(
      app,
      browser: :chrome,
      desired_capabilities: capabilities,
    )
  end

  Capybara.javascript_driver = :chrome
```

I spun that app up months ago, it might not be necessary now.

**Comment by botandrose** [comment]
Hey y'all, long time. I made a gem that wraps all this headless chrome
configuration up, because I couldn't find one already:
https://github.com/botandrose/capybara-headless_chrome . Might fix what
ails ya!

**Comment by aeschright** [comment]
Got it working! I think the window size was the culprit. Now I just need to update the Travis config.
