### ISSUE TITLE
Calagator should support non-Google geocoders

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#57]
Google's geocoder comes with the caveat that you have to display its results on Google map tiles. Yahoo's geocoder comes with similar limitations.

As of #55, we use Leaflet to drive our map display and can pull in map tiles from a number of non-Google sources. In order to support geocoding for these maps while not breaking these terms, we should support other geocoding services.

[GeoKit](/geokit/geokit), which we are using to abstract our geocoding needs, supports many viable options. We should bring these to the surface via configuration in config/secrets.yml.

**Comment by shawnacscott** [comment]
Is this still an outstanding issue?

**Comment by reidab** [comment]
Yep

**Comment by reidab** [comment]
We now expose Geokit configuration directly, so I'm calling this closed.
