### ISSUE TITLE
Rolling back an event deletion does not return it to the search index

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#58]

**Comment by shawnacscott** [comment]
Is this still true?

**Comment by shawnacscott** [comment]
oops, accidental close

**Comment by Sienara** [comment]
Tested this use case recently, seems to be functional. May be able to close this issue.

**Comment by reidab** [comment]
One important thing to consider is that this behavior may differ between our different search providers. We should test using both SQL and Sunspot-based search before closing.
