### ISSUE TITLE
401 error attempting to import a Meetup event

### ISSUE THREAD

**Issue by carrythebanner** [calagator/calagator#593]
1. Navigate to http://calagator.org/sources/new
2. Enter a public Meetup.com event in the URL field (e.g. https://www.meetup.com/Portland-Accessibility-and-User-Experience-Meetup/events/264001273/)
3. Press Import

**Result**: 
There is an error importing, and the event is not created: 
`ERROR: Unable to import: Unknown error: 401 Unauthorized: {"details":"API requests must be key-signed, oauth-signed, or accompanied by a key: https:\/\/www.meetup.com\/meetup_api\/docs\/#authentication","code":"not_authorized","problem":"You are not authorized to make that request"}`

**Comment by aeschright** [comment]
Meetup migrated to a new API and authentication system starting in August 2019. The new API uses GraphQL so the migrator would need a rewrite, but there are other access issues.

**Comment by reidab** [comment]
Closing this for now. We removed the Meetup parser in #681. I've applied for credentials for the new Meetup API. If we're approved for those, we'll open new tickets about that work.
