### ISSUE TITLE
iOS Client

### ISSUE THREAD

**Issue by noahemmet** [calagator/calagator#594]
Hi! I've been finding Calagator pretty useful, and I wanted to play with Apple's new [SwiftUI](https://developer.apple.com/xcode/swiftui/) framework, so I made a little iOS client here: https://github.com/noahemmet/Calagator/

It requires iOS 13, which is currently in [public beta](http://developer.apple.com/download/), but once that's officially released I can submit it to the App Store!

One note, in case anyone's interested: I'm using this [hacked together app icon](https://github.com/noahemmet/Calagator/blob/master/Calagator/Assets.xcassets/AppIcon.appiconset/calagator-site-icon.png) I took from the website, but the finished app [will require a significant number of icon sizes](https://developer.apple.com/library/archive/qa/qa1686/_index.html#Icons%20for%20Universal%20Applications), and it'd be nice to use a more polished icon. If anyone's interested in whipping something up, or if you know of an existing Calagator icon stash, feel free to message me!

**Comment by noahemmet** [comment]
Update: I added some rudimentary icons here: https://github.com/noahemmet/Calagator/tree/master/Assets/App%20Icon

iOS:
![](https://github.com/noahemmet/Calagator/blob/master/Assets/App%20Icon/iPad%20App%2076pt@2x.png?raw=true)

Mac:
![](https://github.com/noahemmet/Calagator/blob/master/Assets/App%20Icon/Mac%20App%20256pt.png?raw=true)

**Comment by noahemmet** [comment]
Oh, this is available on the App Store now: https://apps.apple.com/us/app/calagator-pdx-tech-calendar/id1485957853

**Comment by jc00ke** [comment]
Very nice! Thanks for letting us know, but there's nothing actionable for us to do here. However, adding a link to the `README` would be very cool.
