### ISSUE TITLE
Event cloning tests fail when run on daylight savings transition day

### ISSUE THREAD

**Issue by reidab** [calagator/calagator#65]
./spec/models/event_spec.rb:815 # Event when cloning start_time
./spec/models/event_spec.rb:817 # Event when cloning end_time 

Both of these test rely on a time expressed in terms of (beginning of today) + (n hours), which will fail on days with a nonstandard number of hours.

**Comment by shawnacscott** [comment]
I believe @botandrose fixed this in #314 (https://github.com/calagator/calagator/pull/314#issuecomment-74737034).
