### ISSUE TITLE
Unable to import a meetup event. Reports a 404 error

### ISSUE THREAD

**Issue by NickSchimek** [calagator/calagator#651]
The following error is returned when trying to import this meetup event: https://www.meetup.com/Code-for-PDX/events/hzksxrybcqbmb/
```
ERROR: Unable to import: Unknown error: 404 Not Found
```

**Comment by aeschright** [comment]
Thanks for reporting this! The meetup API endpoint we were using is no longer available, so we'll need to update to the new one. In the meantime I can set up a fallback to use the iCalendar option.

**Comment by aeschright** [comment]
Closing as duplicate of #593
