### ISSUE TITLE
Document: Mobile app(s)

### ISSUE THREAD

**Issue by shawnacscott** [calagator/calagator#89]
These are from the 2014 OSBridge unconference sessions ([Notes](http://opensourcebridge.org/wiki/2014/Calagator))

Currently, there are multiple mobile apps available. @aeschright has written one for iPhone, but there is at least one other iPhone-specific app created (and possibly maintained? Not sure of status of the project) somewhere on GitHub. There is at least one Android app as well.

These should be documented and evaluate opportunities for contributing to these.

**Comment by browniefed** [comment]
Just built https://github.com/browniefed/calagator-react-native if anyone is interested in react native.

**Comment by shawnacscott** [comment]
Thanks for the heads up!
