### ISSUE TITLE
Check in Gemfile.lock

### ISSUE THREAD

**Issue by aeschright** [calagator/calagator#97]
I hear there are some reasons it would not work with the current code to do this, and I think we should fix that.

Reasons:
1) there are a bunch of conditionals in the Gemfile that come from environment variables and configuration settings. These would need to modified to handle the requirements (if they are still needed) in a different way.

**Comment by shawnacscott** [comment]
Now that the engine branch is merged (#314 :tada:), we should be able to move forward with this.

**Comment by reidab** [comment]
With the engine branch merged, we've removed all of the complex custom code from the Gemfile and now rely only on the versions specified in the gemspec. With the new gem layout, it's [best practice](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/) to leave the Gemfile.lock out of version control.

**Comment by shawnacscott** [comment]
:+1:
